version: '3.9'
name: tp1
services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    ports:
      - 15672:15672
    environment:
      - RABBITMQ_LOGS=rabbit.log
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 50s

  client:
    container_name: client
    image: client:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - server
      - query_handler

  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - CONNECTED_NODES=1
    depends_on:
      rabbitmq:
        condition: service_healthy

  initial_column_cleaner_1:
    container_name: initial_column_cleaner_1
    image: column_cleaner:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - INPUT_QUEUE=full_flight_registers
      - OUTPUT_EXCHANGE=cleaned_flight_registers
      - REQUIRED_COLUMNS_FLIGHTS=op_code,legId,startingAirport,destinationAirport,travelDuration,baseFare,totalFare,totalTravelDistance,segmentsArrivalAirportCode
      - CONNECTED_NODES=1
    depends_on:
      - filter_by_three_stopovers_1
      - query_2_column_filter_1
      - query_5_column_filter_1
      - avg_calculator_1
      - filter_by_average_1

  filter_by_three_stopovers_1:
    container_name: filter_by_three_stopovers_1
    image: filter_by_three_stopovers:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - OUTPUT_QUEUE=output_1
      - INPUT_QUEUE=filter_three_stop_overs_queue
      - INPUT_EXCHANGE=cleaned_flight_registers
      - OUTPUT_EXCHANGE=three_or_more_stopovers
      - COLUMNS_TO_FILTER=op_code,legId,startingAirport,destinationAirport,stopovers,totalFare
    depends_on:
      - group_by_route

  query_2_column_filter_1:
    container_name: query_2_column_filter_1
    image: column_cleaner:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - INPUT_EXCHANGE=cleaned_flight_registers
      - INPUT_QUEUE=query_2_filter_queue
      - OUTPUT_EXCHANGE=airport_registers
      - OUTPUT_QUEUE=distance_calculation
      - REQUIRED_COLUMNS_FLIGHTS=op_code,legId,startingAirport,destinationAirport,totalTravelDistance,segmentsArrivalAirportCode
      - REQUIRED_COLUMNS_AIRPORTS=op_code,Airport Code,Latitude,Longitude
      - ROUTING_KEY=all
    depends_on:
      - distance_calculator_1

  distance_calculator_1:
    container_name: distance_calculator_1
    image: distance_calculator:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - INPUT_QUEUE=distance_calculation
      - OUTPUT_QUEUE=output_2
      - INPUT_EXCHANGE=airport_registers
    depends_on:
      - query_handler

  group_by_route:
    container_name: group_by_route
    image: group_by:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - REDUCERS_AMOUNT=2
      - FIELD_GROUP_BY=startingAirport,destinationAirport
      - INPUT_EXCHANGE=three_or_more_stopovers
      - QUEUE_GROUP_BY=group_by_route_queue
      - LISTENING_QUEUE=group_by_route
      - INPUT_QUEUE=
    depends_on:
      - reducer_group_by_route_1
      - reducer_group_by_route_2

  reducer_group_by_route_1:
    container_name: reducer_group_by_route_1
    image: reducer_group_by:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - FIELD_GROUP_BY=route
      - INPUT_QUEUE=group_by_route_queue_1
      - OUTPUT_QUEUE=output_3
      - QUERY_NUMBER=3
    depends_on:
      - query_handler

  reducer_group_by_route_2:
    container_name: reducer_group_by_route_2
    image: reducer_group_by:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - FIELD_GROUP_BY=route
      - INPUT_QUEUE=group_by_route_queue_2
      - OUTPUT_QUEUE=output_3
      - QUERY_NUMBER=3
    depends_on:
      - query_handler

  query_5_column_filter_1:
    container_name: query_5_column_filter_1
    image: column_cleaner:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - INPUT_EXCHANGE=cleaned_flight_registers
      - INPUT_QUEUE=query_5_filter_queue
      - OUTPUT_QUEUE=mode_calculation
      - REQUIRED_COLUMNS_FLIGHTS=op_code,startingAirport,baseFare
      - CONNECTED_NODES=1
      - ROUTING_KEY=flights
    depends_on:
      - group_by_airport

  group_by_airport:
    container_name: group_by_airport
    image: group_by:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - REDUCERS_AMOUNT=2
      - FIELD_GROUP_BY=startingAirport
      - INPUT_EXCHANGE=
      - LISTENING_QUEUE=
      - QUEUE_GROUP_BY=group_by_airport_queue
      - INPUT_QUEUE=mode_calculation
    depends_on:
      - reducer_group_by_airport_1
      - reducer_group_by_airport_2

  reducer_group_by_airport_1:
    container_name: reducer_group_by_airport_1
    image: reducer_group_by:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - FIELD_GROUP_BY=startingAirport
      - INPUT_QUEUE=group_by_airport_queue_1
      - OUTPUT_QUEUE=output_5
      - QUERY_NUMBER=5
    depends_on:
      - query_handler

  reducer_group_by_airport_2:
    container_name: reducer_group_by_airport_2
    image: reducer_group_by:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - FIELD_GROUP_BY=startingAirport
      - INPUT_QUEUE=group_by_airport_queue_2
      - OUTPUT_QUEUE=output_5
      - QUERY_NUMBER=5
    depends_on:
      - query_handler

  avg_calculator_1:
    container_name: avg_calculator_1
    image: avg_calculator:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - INPUT_QUEUE=avg_queue
      - OUTPUT_EXCHANGE=flights_avg
      - INPUT_EXCHANGE=cleaned_flight_registers
    depends_on:
      - filter_by_average_1

  filter_by_average_1:
    container_name: filter_by_average_1
    image: filter_by_average:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - INPUT_QUEUE=cleaned_column_queue
      - OUTPUT_QUEUE=filtered_by_average
      - INPUT_EXCHANGE_1=flights_avg
      - INPUT_EXCHANGE_2=cleaned_flight_registers
      - ID=1
    depends_on:
      - group_by_route_query_4

  group_by_route_query_4:
    container_name: group_by_route_query_4
    image: group_by:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - REDUCERS_AMOUNT=2
      - EOF_REQUIRED=1
      - FIELD_GROUP_BY=startingAirport,destinationAirport
      - LISTENING_QUEUE=
      - INPUT_EXCHANGE=
      - QUEUE_GROUP_BY=group_by_route_queue_q4
      - INPUT_QUEUE=filtered_by_average
    depends_on:
      - reducer_group_by_route_q4_1
      - reducer_group_by_route_q4_2

  reducer_group_by_route_q4_1:
    container_name: reducer_group_by_route_q4_1
    image: reducer_group_by:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - FIELD_GROUP_BY=route
      - INPUT_QUEUE=group_by_route_queue_q4_1
      - OUTPUT_QUEUE=output_4
      - QUERY_NUMBER=4
    depends_on:
      - query_handler

  reducer_group_by_route_q4_2:
    container_name: reducer_group_by_route_q4_2
    image: reducer_group_by:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - FIELD_GROUP_BY=route
      - INPUT_QUEUE=group_by_route_queue_q4_2
      - OUTPUT_QUEUE=output_4
      - QUERY_NUMBER=4
    depends_on:
      - query_handler

  query_handler:
    container_name: query_handler
    image: query_handler:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - TOTAL_REDUCERS=2
      - LISTEN_BACKLOG=1
    depends_on:
      rabbitmq:
        condition: service_healthy
